"""Alpha research APIs for factor discovery, modeling, and signal artifacts."""

__all__ = [
    "artifact_cpcv",
    "cpcv",
    "cpcv_audit",
    "dynamic_signal_ensemble",
    "factor_diagnostics",
    "factor_diagnostics_config",
    "factor_diagnostics_math",
    "evaluation",
    "feature_dataset",
    "feature_engineering",
    "feature_evidence",
    "modeling",
    "overfitting_diagnostics",
    "pbo",
    "period_evaluation",
    "research_dataset",
    "research_model",
    "signal_artifact",
    "signal_stability",
    "split",
    "train_eval",
    "train_eval_fit",
    "train_eval_stage",
    "transform",
    "walk_forward",
]
